### ISSUE TITLE
Issue error if SuSo chars DNE for command that requires them

### ISSUE THREAD

**Issue by arthur-shaw** [lsms-worldbank/selector#15]
If a selector command that requires SuSo questionnaire metadata chars, check that chars exist. If yes, silently continue. If no, fail helpfully so that the user knows metadata must be attached before the command can be executed.

This list may not be exhaustive:

- [x] sel_vars (look for specific chars)
- [x] sel_char (need to look for any char)
- [x] sel_remove_metadata (if no chars attached anyway)

**Comment by kbjarkefur** [comment]
This is "char does not exists withing the varlist used" which can be a subset of all variables.

Test if `char _dta[selector_chars]` as a artifact for whether the meta data has been applied
